
--Select BY CART ID procedure
CREATE OR REPLACE PROCEDURE SELECT_CART_BY_CART_ID(ID IN NUMBER,CUSTOMER_ID OUT NUMBER,FOOD_ID OUT NUMBER,QTY OUT NUMBER,SUBTOTAL OUT NUMBER)
IS
BEGIN
    SELECT CART_CUSTOMER_ID , CART_FOOD_ID , CART_QUANTITY , CART_SUB_TOTAL 
    INTO CUSTOMER_ID , FOOD_ID , QTY , SUBTOTAL
    FROM CART_TABLE
    WHERE CART_ID = ID;        
END SELECT_CART_BY_CART_ID;


--DELETE BY CUS ID PROCEDURE
CREATE OR REPLACE PROCEDURE DELETE_BY_CUSTOMER_ID(CUSTOMER_ID IN NUMBER)
IS
BEGIN
    DELETE FROM CART_TABLE 
    WHERE CART_CUSTOMER_ID = CUSTOMER_ID;
END DELETE_BY_CUSTOMER_ID;

--DELETE BY CART ID PROCEDURE
CREATE OR REPLACE PROCEDURE DELETE_BY_CART_ID(ID IN NUMBER)
IS
BEGIN
    DELETE FROM CART_TABLE
    WHERE CART_ID = ID;
END DELETE_BY_CART_ID;

--INSERT DATA
CREATE OR REPLACE PROCEDURE INSERT_CART_DATA(CUSTOMER_ID IN NUMBER, FOOD_ID IN NUMBER,QTY IN NUMBER,SUBTOTAL IN NUMBER)
IS
BEGIN
    INSERT 
    INTO CART_TABLE (CART_CUSTOMER_ID , CART_FOOD_ID , CART_QUANTITY , CART_SUB_TOTAL)
    VALUES (CUSTOMER_ID , FOOD_ID , QTY , SUBTOTAL);
END INSERT_CART_DATA;

