--get all orders
CREATE OR REPLACE PROCEDURE GET_ALL_ORDERS(order_result OUT SYS_REFCURSOR)
AS
BEGIN
    OPEN order_result FOR
    SELECT ORDER_ID , order_total_price, order_customer_id FROM ORDER_TABLE;

END GET_ALL_ORDERS;

--get order by orderid
CREATE OR REPLACE PROCEDURE GET_ORDER_BY_ID(ORDERID IN NUMBER , ORDER_TOTAL_PRICE OUT VARCHAR2 , ORDER_CUSTOMER_ID OUT NUMBER )
AS
BEGIN
    SELECT  order_total_price, order_customer_id
    INTO  ORDER_TOTAL_PRICE , ORDER_CUSTOMER_ID
    FROM ORDER_TABLE
    WHERE ORDER_ID = ORDERID;
END GET_ORDER_BY_ID;

--insert an order
CREATE OR REPLACE PROCEDURE INSERT_ORDER_DATA (
    TOTAL_PRICE IN NUMBER,
    CUSTOMER_ID IN NUMBER,
    P_ORDER_ID OUT NUMBER
)
AS
BEGIN
    INSERT INTO ORDER_TABLE (ORDER_TOTAL_PRICE, ORDER_CUSTOMER_ID)
    VALUES (TOTAL_PRICE, CUSTOMER_ID)
    RETURNING ORDER_ID INTO P_ORDER_ID;
END INSERT_ORDER_DATA;

----update an order
--CREATE OR REPLACE PROCEDURE UPDATE_ORDER_DATA(ID IN NUMBER, STATUS IN VARCHAR2)
--IS
--BEGIN
--    UPDATE ORDER_TABLE
--    SET ORDER_STATUS = STATUS
--    WHERE ORDER_ID = ID;
--END UPDATE_ORDER_DATA;






