--get all orders
CREATE OR REPLACE PROCEDURE GET_ALL_ORDERS(order_result OUT SYS_REFCURSOR)
AS
BEGIN
    OPEN order_result FOR
    SELECT ORDER_ID , order_total_price, order_customer_id, order_status FROM ORDER_TABLE;

END GET_ALL_ORDERS;

--insert an order
CREATE OR REPLACE PROCEDURE INSERT_ORDER_DATA (
    TOTAL_PRICE IN NUMBER,
    CUSTOMER_ID IN NUMBER,
    STATUS IN VARCHAR2,
    P_ORDER_ID OUT NUMBER
)
AS
BEGIN
    INSERT INTO ORDER_TABLE (ORDER_TOTAL_PRICE, ORDER_CUSTOMER_ID, ORDER_STATUS)
    VALUES (TOTAL_PRICE, CUSTOMER_ID, STATUS)
    RETURNING ORDER_ID INTO P_ORDER_ID;
END INSERT_ORDER_DATA;

--update an order
CREATE OR REPLACE PROCEDURE UPDATE_ORDER_DATA(ID IN NUMBER, STATUS IN VARCHAR2)
IS
BEGIN
    UPDATE ORDER_TABLE
    SET ORDER_STATUS = STATUS
    WHERE ORDER_ID = ID;
END UPDATE_ORDER_DATA;






