--insert data to suborder
CREATE OR REPLACE PROCEDURE INSERT_DATA_TO_SUBORDER(CUSTOMER_ID IN NUMBER,FOOD_ID IN NUMBER, QTY IN NUMBER, ORDER_ID IN NUMBER)
IS 
BEGIN
    INSERT 
    INTO SUBORDER_TABLE (SUBORDER_CUSTOMER_ID , SUBORDER_FOOD_ID , SUBORDER_QTY , SUBORDER_ORDER_ID)
    VALUES (CUSTOMER_ID , FOOD_ID , QTY , ORDER_ID);
END INSERT_DATA_TO_SUBORDER;

--select suborder by order id
CREATE OR REPLACE PROCEDURE SELECT_SUBORDER_BY_ORDER_ID(ORDER_ID IN NUMBER,CUSTOMER_ID OUT NUMBER, FOOD_ID OUT NUMBER, QTY OUT NUMBER)
IS
BEGIN
    SELECT SUBORDER_CUSTOMER_ID , SUBORDER_FOOD_ID , SUBORDER_QTY
    INTO CUSTOMER_ID , FOOD_ID ,  QTY
    FROM SUBORDER_TABLE
    WHERE SUBORDER_ORDER_ID = ORDER_ID;
END SELECT_SUBORDER_BY_ORDER_ID;