--insert data to suborder
CREATE OR REPLACE PROCEDURE INSERT_DATA_TO_SUBORDER(FOOD_ID IN NUMBER, QTY IN NUMBER, ORDER_ID IN NUMBER , SUPPLIER_ID IN NUMBER, STATUS IN VARCHAR2)
IS
BEGIN
    INSERT
    INTO SUBORDER_TABLE ( SUBORDER_FOOD_ID , SUBORDER_QTY , SUBORDER_ORDER_ID , SUBORDER_SUPPLIER_ID, SUBORDER_STATUS)
    VALUES ( FOOD_ID , QTY , ORDER_ID , SUPPLIER_ID , STATUS);
END INSERT_DATA_TO_SUBORDER;

--select suborder by order id
CREATE OR REPLACE PROCEDURE SELECT_SUBORDER_BY_ORDER_ID(ORDER_ID IN NUMBER , SUB_ORDER_RESULT OUT SYS_REFCURSOR)
AS
BEGIN
    OPEN SUB_ORDER_RESULT FOR
    SELECT SUBORDER_ID , SUBORDER_FOOD_ID , SUBORDER_QTY , SUBORDER_ORDER_ID , SUBORDER_SUPPLIER_ID , SUBORDER_STATUS
    FROM SUBORDER_TABLE
    WHERE SUBORDER_ORDER_ID = ORDER_ID;
END SELECT_SUBORDER_BY_ORDER_ID;

--select suborder by supplier id
CREATE OR REPLACE PROCEDURE SELECT_SUBORDER_BY_SUPPLIER_ID(SUPPLIER_ID IN NUMBER , SUB_ORDER_RESULT OUT SYS_REFCURSOR)
AS
BEGIN
    OPEN SUB_ORDER_RESULT FOR
    SELECT SUBORDER_ID , SUBORDER_FOOD_ID , SUBORDER_QTY , SUBORDER_ORDER_ID , SUBORDER_SUPPLIER_ID , SUBORDER_STATUS
    FROM SUBORDER_TABLE
    WHERE SUBORDER_SUPPLIER_ID = SUPPLIER_ID;
END SELECT_SUBORDER_BY_SUPPLIER_ID;