--SUPPLIER LOGIN
CREATE OR REPLACE PROCEDURE LOGIN_SUPPLIER(NAME IN VARCHAR2,PASSWORD IN VARCHAR2,ID OUT NUMBER)
IS
BEGIN
    SELECT SUPPLIER_ID
    INTO ID
    FROM SUPPLIER_TABLE
    WHERE SUPPLIER_NAME = NAME AND SUPPLIER_PASSWORD = PASSWORD;
    
EXCEPTION
    WHEN NO_DATA_FOUND THEN
        ID := 0;
END;

--Register supplier--
CREATE OR REPLACE PROCEDURE REGISTER_SUPPLIER(SNAME IN VARCHAR2, ADDRESS IN VARCHAR2, TELL IN NUMBER, COMPANY IN VARCHAR2, PASSWORD IN VARCHAR2)
IS
BEGIN
    INSERT
    INTO SUPPLIER_TABLE(SUPPLIER_NAME, SUPPLIER_ADDRESS, SUPPLIER_TEL, SUPPLIER_COMPANY, SUPPLIER_PASSWORD)
    VALUES (SNAME, ADDRESS, TELL, COMPANY, PASSWORD);
END REGISTER_SUPPLIER;



--Get all suppliers--
create or replace PROCEDURE GET_ALL_SUPPLIERS(supplier_result OUT SYS_REFCURSOR)
AS
BEGIN
    OPEN supplier_result FOR
    SELECT supplier_name, supplier_address, supplier_tel, supplier_company, supplier_password FROM SUPPLIER_TABLE;
    EXCEPTION 
   WHEN no_data_found THEN 
      dbms_output.put_line('No suppliers found!'); 

END GET_ALL_SUPPLIERS;



--Get supplier id--
create or replace PROCEDURE GET_SUPPLIER_BY_ID(ID IN NUMBER, NAME OUT VARCHAR2, ADDRESS OUT VARCHAR2, TELL OUT NUMBER, COMPANY OUT VARCHAR2, PASSWORD OUT VARCHAR2)
AS
BEGIN
    SELECT SUPPLIER_NAME, SUPPLIER_ADDRESS, SUPPLIER_TEL, SUPPLIER_COMPANY, SUPPLIER_PASSWORD INTO NAME, ADDRESS, TELL, COMPANY, PASSWORD FROM SUPPLIER_TABLE WHERE SUPPLIER_ID = ID;
    EXCEPTION 
   WHEN no_data_found THEN 
      dbms_output.put_line('No such supplier!'); 
END GET_SUPPLIER_BY_ID;



--Update supplier by id
create or replace PROCEDURE UPDATE_SUPPLIER(ID IN NUMBER, NAME IN VARCHAR2, ADDRESS IN VARCHAR2, TELL IN NUMBER, COMPANY IN VARCHAR2, PASSWORD IN VARCHAR2)
AS
BEGIN
    UPDATE SUPPLIER_TABLE
    SET SUPPLIER_NAME = NAME, SUPPLIER_ADDRESS = ADDRESS, SUPPLIER_TEL = TELL, SUPPLIER_COMPANY = COMPANY, SUPPLIER_PASSWORD = PASSWORD
    WHERE SUPPLIER_ID = ID;
    EXCEPTION 
   WHEN no_data_found THEN 
      dbms_output.put_line('No such supplier!'); 
    
END UPDATE_SUPPLIER;

--Delete supplier by id
create or replace PROCEDURE DELETE_SUPPLIER(ID IN NUMBER)
AS
BEGIN
    DELETE FROM SUPPLIER_TABLE
    WHERE SUPPLIER_ID = ID;
    EXCEPTION 
   WHEN no_data_found THEN 
      dbms_output.put_line('No such supplier!'); 
END DELETE_SUPPLIER;
