--SUPPLIER LOGIN
CREATE OR REPLACE PROCEDURE LOGIN_SUPPLIER(NAME IN VARCHAR2,PASSWORD IN VARCHAR2,ID OUT NUMBER)
IS
BEGIN
    SELECT SUPPLIER_ID
    INTO ID
    FROM SUPPLIER_TABLE
    WHERE SUPPLIER_NAME = NAME AND SUPPLIER_PASSWORD = PASSWORD;
    
EXCEPTION
    WHEN NO_DATA_FOUND THEN
        ID := 0;
END;